import React from "react";

export function Albums() {
  return (
    <div className="albums-body">
      <h2 className="text-4xl sm:text-5xl text-center leading-normal">
        Albums
      </h2>
      <ul>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
        <li>Album1 </li>
        <li>Album 2</li>
        <li>Album 3</li>
        <li>Album 4</li>
      </ul>
    </div>
  );
}
